// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADOQ_tG2eQT3P3Hn7hzK1IaSNZMqwpryE',
    appId: '1:393307584987:web:f2577c6dedc6770e390ffe',
    messagingSenderId: '393307584987',
    projectId: 'reunion-62bcd',
    authDomain: 'reunion-62bcd.firebaseapp.com',
    storageBucket: 'reunion-62bcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0xF5ggV-TT-5jS_hgBfd1We6PEgeuqOM',
    appId: '1:393307584987:android:e35727a43c62e1e9390ffe',
    messagingSenderId: '393307584987',
    projectId: 'reunion-62bcd',
    storageBucket: 'reunion-62bcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmWmjmR7JFBWLeZKujDIzFhDfI5NLwt2k',
    appId: '1:393307584987:ios:25e79743498e296a390ffe',
    messagingSenderId: '393307584987',
    projectId: 'reunion-62bcd',
    storageBucket: 'reunion-62bcd.appspot.com',
    androidClientId: '393307584987-l29kd5vecn84foltnetofag2p18e130d.apps.googleusercontent.com',
    iosClientId: '393307584987-ed0m17sjvqnkpkpe70hneq4385g2dhqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.reunion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmWmjmR7JFBWLeZKujDIzFhDfI5NLwt2k',
    appId: '1:393307584987:ios:25e79743498e296a390ffe',
    messagingSenderId: '393307584987',
    projectId: 'reunion-62bcd',
    storageBucket: 'reunion-62bcd.appspot.com',
    androidClientId: '393307584987-l29kd5vecn84foltnetofag2p18e130d.apps.googleusercontent.com',
    iosClientId: '393307584987-ed0m17sjvqnkpkpe70hneq4385g2dhqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.reunion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADOQ_tG2eQT3P3Hn7hzK1IaSNZMqwpryE',
    appId: '1:393307584987:web:1736cce74c5579ea390ffe',
    messagingSenderId: '393307584987',
    projectId: 'reunion-62bcd',
    authDomain: 'reunion-62bcd.firebaseapp.com',
    storageBucket: 'reunion-62bcd.appspot.com',
  );

}